#SPDX-License-Identifier: MIT-0
---
# tasks file for app

- name: Ensure target directory exists
  ansible.builtin.file:
    path: "{{ web_root }}"
    state: directory
    owner: root
    group: root 
    mode: '0755'

- name: Upload website tarball
  ansible.builtin.copy:
    src: website.tar.gz
    dest: /tmp/website.tar.gz
    mode: '0644'

- name: Extract website tarball
  ansible.builtin.unarchive:
    src: /tmp/website.tar.gz
    dest: "{{ web_root }}"
    remote_src: yes
    owner: www-data
    group: www-data
    mode: '0755'
  notify: Restart Nginx

# - name: Deploy Nginx configuration
#   ansible.builtin.template:
#     src: nginx.conf.j2
#     dest: /etc/nginx/sites-available/static-site
#     owner: root
#     group: root
#     mode: '0644'
#   notify: Restart Nginx

# - name: Enable Nginx site
#   ansible.builtin.file:
#     src: /etc/nginx/sites-available/static-site
#     dest: /etc/nginx/sites-enabled/static-site
#     state: link
#   notify: 
#     - Restart Nginx
