#SPDX-License-Identifier: MIT-0
---
# tasks file for app

- name: Ensure target directory exists
  ansible.builtin.file:
    path: "{{ web_root }}"
    state: directory
    owner: root
    group: root 
    mode: '0755'

- name: Upload website tarball
  ansible.builtin.copy:
    src: index.tar.gz
    dest: /tmp/index.tar.gz
    mode: '0644'

- name: Extract website tarball
  ansible.builtin.unarchive:
    src: /tmp/index.tar.gz
    dest: "{{ web_root }}"
    remote_src: yes
    owner: www-data
    group: www-data
    mode: '0755'
  notify: Restart Nginx



