#SPDX-License-Identifier: MIT-0
---
# tasks file for base


# ================== UPDATE LINUX SERVERS ===================================
- name: update pagages 
  block:    
  - name: Update apt repo and cache on all Debian/Ubuntu Servers
    ansible.builtin.apt:
      update_cache: yes 
      force_apt_get: yes 
      cache_valid_time: 3600
      install_recommends: yes
    when: ansible_os_family == "Debian"

  - name: Update yum repo and cache on all RedHat  Servers
    ansible.builtin.yum:
      name: "*"
      state: latest
    when: ansible_os_family == "RedHat"


  - name: Upgrade all packages on Debian/Ubuntu servers
    ansible.builtin.apt:
      upgrade: dist     
      only_upgrade: true
      state: latest
    when: ansible_os_family == ["Debian","Ubuntu"]
  rescue:
    - name:
      ansible.builtin.debug:
        msg: " An error occured while updating packages"
  # always:


  # ================== INSTALL fail2ban ===================================
- name: update pagages 
  block:
    - name: Install fail2ban
      ansible.builtin.package:
        name: fail2ban      
        state: present

    - name: start fail2ban service
      ansible.builtin.service:
        name: fail2ban
        state: started
        enabled: yes
  rescue:
   -  name:
      ansible.builtin.debug:
        msg: " An error occured while installing fail2ban"



 # ================== INSTALL utilities ===================================
- name: Install utilities
  ansible.builtin.package:
    name:
      - curl
      - wget
      - vim
      - htop
      - git
    state: present 
    
 

    
